# Generated by Django 5.0.6 on 2024-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quaniti',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
